services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server","--appendonly","yes","--appendfsync","everysec"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  api:
    build: .
    container_name: api-leads-toxo-dev
    ports:
      - "3000:3000"   # Puerto expuesto para desarrollo
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - NODE_ENV=development
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
volumes:
  redis-data:
