services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server","--appendonly","yes","--appendfsync","everysec"]
    volumes:
      - redis-data:/data
volumes:
  redis-data:
